
CREATE DATABASE UDEMY_SQL_RH
USE UDEMY_SQL_RH

CREATE TABLE FUNCIONARIOS
(
	 ID_FUN			INT IDENTITY (1,2) -- INSERI UM REGISTRO DE 2 EM 2 
	,SEXO			VARCHAR(255)
	,NOME			VARCHAR(255)
	,ENDERECO		VARCHAR(255)
	,SALARIO		DECIMAL(5,4)
)

-- inserir registros
INSERT INTO		
		FUNCIONARIOS
VALUES			
		('LUCAS', 'MASCULINO', 'SOUSA LONGO', 1.500)


INSERT INTO		
	FUNCIONARIOS
VALUES			
		('LAURA', 'FEMININO', 'SOUSA BREVES', 5.500)

-- Inserindo em lotes
INSERT INTO		
	FUNCIONARIOS
VALUES			
		('LAURA', 'FEMININO', 'SOUSA BREVES', 5.500),
		('TONY', 'MASCULINO', 'SOUSA BREVES', 8.500),
		('NINA', 'FEMININO', 'SOUSA BREVES',  4.300)



-- Consultando as tabelas
SELECT	*
FROM	FUNCIONARIOS


